name: Build Docker Image

on: [push]

jobs:

  build:

    runs-on: ubuntu-18.04

    steps:
    - uses: actions/checkout@v2
    - name: Build the Docker image
      run: docker build ./alpine --tag nexusrepomanoss:$(date +%s)
